Document: musikernel2
Title: Debian musikernel2 Manual
Author: <insert document author here>
Abstract: This manual describes what musikernel2 is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/musikernel2/musikernel2.sgml.gz

Format: postscript
Files: /usr/share/doc/musikernel2/musikernel2.ps.gz

Format: text
Files: /usr/share/doc/musikernel2/musikernel2.text.gz

Format: HTML
Index: /usr/share/doc/musikernel2/html/index.html
Files: /usr/share/doc/musikernel2/html/*.html
